export const THEMES = [
  { name: "light", label: "Godspeed" },
  { name: "dark", label: "Zoom" },
  { name: "bumblebee", label: "The Flash" },
  { name: "emerald", label: "Savitar" },
  { name: "corporate", label: "Vibe" },
  { name: "synthwave", label: "Iris West" },
  { name: "retro", label: "Jay Garrick" },
  { name: "valentine", label: " XS" },
  { name: "halloween", label: "Monitor" },
  { name: "garden", label: "Jesse Quick" },
  { name: "forest", label: "FireStorm" },
  { name: "aqua", label: "Captain Cold" },
  { name: "wireframe", label: "Anti-Monitor" },
  { name: "black", label: "Black Flash" },
  { name: "luxury", label: "Reverse Flash" },
  { name: "dracula", label: "Heat Wave" },
  { name: "cmyk", label: "Print Vibes" },
  { name: "autumn", label: "Fall Harvest" },
  { name: "business", label: "Professional Gray" },
  { name: "acid", label: "Toxic Glow" },
  { name: "lemonade", label: "Max Mercury" },
  { name: "night", label: "Kid Flash" },
  { name: "coffee", label: "Bart Allen" },
  { name: "winter", label: "Killer Frost" },
];
